[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "wmhparc"
version = "1.0.0"
description = "WMHParc — tools for WMH bullseye parcellation"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }

authors = [
  { name = "Ben Philps", email = "bphilps@ed.ac.uk" },
]

dependencies = [
  "SimpleITK==2.4.0",
  "antspyx==0.5.4",
  "jupyterlab==4.3.4",
  "matplotlib==3.10.0",
  "matplotlib-inline==0.1.7",
  "numpy==1.26.4",
  "pandas==2.2.3",
  "scipy==1.14.1",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["wmhparc*"]
